server:
  port: 8400

canal:
  client:
    instances:
      example:
        acquireInterval: 1000
        batchSize: 1000
        clusterEnabled: false
        host: ${young-canal}
        port: 11111
        retryCount: 20

spring:
  boot:
    admin:
      client:
        url: http://${young-admin}:8500
        username: young
        password: 123456

  redis:
    database: 0
    host: ${redis.url}
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    password: 123456
  main:
    allow-bean-definition-overriding: true

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS