server:
  port: 8200

spring:
  datasource:
    dynamic:
      #要开启p6spy功能,p6spy用于在控制台中打印MyBatis执行的SQL。
      #p6spy适合在开发环境用于问题分析，其会带来一定的性能耗损，
      #所以在生产环境这个配置最好改为false，将其关闭
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: youngHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${mysql.url}:13306/young_cloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
  redis:
    database: 0
    host: ${redis.url}
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    password: 123456


security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://${young-gateway}:8100/auth/user

#user-info-uri路径为http://localhost:8301/auth/user，通过微服务网关，
#该请求将被转发到http://localhost:8101/user。该配置的作用主要有两个：
#1、到认证服务器里校验当前请求头中的令牌是否为合法的令牌；
#2、通过当前令牌获取对应的用户信息。

mybatis-plus:
  type-aliases-package: com.system.*
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
  global-config:
    banner: false

rocketmq:
  name-server: ${rocketmq.url}:9876
  producer:
    group: test-group