server:
  port: 8100

spring:
  boot:
    admin:
      client:
        url: http://${young-admin}:8500
        username: young
        password: 123456

  redis:
    database: 0
    host: ${redis.url}
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    password: 123456

#让Feign的回退生效,因为Feign的回退功能是基于Hystrix实现的，所以需要开启它。
feign:
  hystrix:
    enabled: true
#请求拦截器能够顺利获取到令牌,这样做会把SecurityContext对象从你当前主线程传输到Hystrix线程。
hystrix:
  shareSecurityContext: true

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS